
# Author: Aniruddha Gokhale
# Vanderbilt University
# Created May 2017,
# Modified Nov 2017
# Modified Oct 2018
# Modified Oct 2019 to use Python3
#
# For Cloud Computing class
#
# First, use the latest ubuntu image, which points to the
# latest LTS image, currently 20.04LTS
FROM ubuntu:latest
#
# Now install the needed python packages
RUN apt-get -y update && apt-get install -y net-tools python3 gcc
RUN apt-get install -y python3-dev python3-pip
RUN python3 -m pip install --upgrade pip
RUN pip3 install --upgrade numpy
RUN apt update

# Now install the needed java package
RUN apt-get install default-jdk

# Now install Kafka 
# RUN wget https://archive.apache.org/dist/kafka/2.8.0/kafka_2.12-2.8.0.tgz
# RUN tar -xzf kafka_2.12-2.8.0.tgz
RUN wget http://mirror.cogentco.com/pub/apache/kafka/2.6.0/kafka_2.13-2.6.0.tgz
RUN zcat kafka_2.13-2.6.0.tgz | tar xpof-


#
# Next, copy our matrix inverse code into the container
# COPY *.py /
#
# Run a command shell (for Swarm and Kubernetes, we comment this out)
#CMD /bin/bash
